### ISSUE TITLE
TODO for version 1.0

### ISSUE THREAD

**Issue by arhad** [arhad/wdk#1]
The first release is intended to contain Material Editor only. The editor must support these features:
- Editing:
    - [ ] Flowchart representation of a material.
    - [ ] Properties.
    - [ ] Support of operations that do not require any import or external dependency.
    - [ ] Simple preview on per-node basis.
- Data exchange:
    - [ ] Saving to and loading from files of proprietary format.
    - [ ] Working with system clipboard.
- Organization:
    - [ ] “Readme” file with a little of usage help.
    - [ ] Versioning policy and tools for providing this.
    - [ ] An auxilary software for shipping the release onto customer`s machines.
