### ISSUE TITLE
TODO for version 1.1

### ISSUE THREAD

**Issue by arhad** [arhad/wdk#2]
This release is intended to provide an integration of Material Editor with its environment. The editor must support these features:
- Editing:
    - [ ] Commenting areas.
    - [ ] Dealing with imported files and extra dependency.
    - [ ] Enhanced preview in separate window or panel based on planar view and 3D models.
- Organization:
    - [ ] Windows shell integration.
    - [ ] CI introducing and night releases.
