### ISSUE TITLE
TODO for version 1.1.1

### ISSUE THREAD

**Issue by arhad** [arhad/wdk#3]
- Project-specific
    - [ ] Add internationalization.
    - Add a general help:
        - [ ] Features.
        - [ ] Nodes documentation.
        - [ ] Examples and HowTo`s.
    - [ ] Add context help.
- General:
    - [ ] CI introduction and night releases.
    - [ ] Add a site.
